- name: create jenkins jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-Pipelines"}
      - { folder_name: "Infra-Jobs"}
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/Tirupathi1729/cart.git", folder_name: "CI-Pipelines" }
      - { job_name: "catalogue", repo_name: "https://github.com/Tirupathi1729/catalogue.git", folder_name: "CI-Pipelines" }
      - { job_name: "user", repo_name: "https://github.com/Tirupathi1729/user.git", folder_name: "CI-Pipelines" }
      - { job_name: "shipping", repo_name: "https://github.com/Tirupathi1729/shipping.git", folder_name: "CI-Pipelines" }
      - { job_name: "payment", repo_name: "https://github.com/Tirupathi1729/payment.git", folder_name: "CI-Pipelines" }
      - { job_name: "frontend", repo_name: "https://github.com/Tirupathi1729/frontend.git", folder_name: "CI-Pipelines" }

    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/Tirupathi1729/roboshop-terraform.git", folder_name: "Infra-Jobs" }